name: Feature request
description: Propose a feature
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe requested functionality.
    validations:
      required: true
